//! Async CAN USB Client - 支持 Channel 风格 Split 和独占 Client 两种模式
//! todo : optimize code generated by ai
use crate::frame::Frame;
use crate::protocol::{build_data_frame, build_settings_frame, parse_frames};
use crate::types::CanUsbConfig;
use std::sync::Arc;
use std::time::Duration;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::sync::{mpsc, Mutex};
use tokio::time::{sleep, timeout};
use tokio_serial::SerialPortBuilderExt;
use tracing::{error, info, trace};
use zencan_common::{CanId, CanMessage};

/// Client errors
#[derive(Debug, thiserror::Error)]
pub enum ClientError {
	#[error("Serial port error: {0}")]
	Serial(#[from] tokio_serial::Error),
	#[error("IO error: {0}")]
	Io(#[from] std::io::Error),
	#[error("Frame too large")]
	FrameTooLarge,
	#[error("Write timeout")]
	WriteTimeout,
	#[error("Read timeout")]
	ReadTimeout,
	#[error("Send error")]
	SendError(#[from] mpsc::error::SendError<CanMessage>),
	#[error("Frame send error")]
	FrameSendError(#[from] mpsc::error::SendError<Frame>),
	#[error("Channel closed")]
	ChannelClosed,
}

// ============================================
// Split 模式：Channel 风格
// ============================================

/// 发送端 Sender - 通过 channel 发送 Frame，后台任务实际写入串口
#[derive(Clone)]
pub struct CanUsbSender {
	frame_tx: mpsc::Sender<Frame>,
}

impl CanUsbSender {
	/// 异步发送 CAN 帧（非阻塞，缓冲到 channel）
	pub async fn send(&self, frame: Frame) -> Result<(), ClientError> {
		self.frame_tx.send(frame).await.map_err(Into::into)
	}

	/// 尝试发送（非阻塞）
	pub fn try_send(&self, frame: Frame) -> Result<(), mpsc::error::TrySendError<Frame>> {
		self.frame_tx.try_send(frame)
	}

	/// 检查 channel 是否关闭
	pub fn is_closed(&self) -> bool {
		self.frame_tx.is_closed()
	}
}

/// 创建 Split 模式，返回 (sender, receiver)
///
/// sender 可以 clone，支持多生产者并发发送
/// receiver 是唯一的，用于接收 CAN 消息
pub async fn split(
	config: CanUsbConfig,
) -> Result<(CanUsbSender, mpsc::Receiver<CanMessage>), ClientError> {
	info!("Creating Split mode: {} @ {} baud", config.device, config.baudrate);

	// 打开串口
	let serial = tokio_serial::new(&config.device, config.baudrate)
		.data_bits(tokio_serial::DataBits::Eight)
		.stop_bits(tokio_serial::StopBits::Two)
		.parity(tokio_serial::Parity::None)
		.open_native_async()?;

	let serial = Arc::new(Mutex::new(serial));

	// 创建 channel：发送 Frame 的 channel（用户 -> 后台写入任务）
	let (frame_tx, frame_rx) = mpsc::channel::<Frame>(100);
	// 接收 CanMessage 的 channel（后台读取任务 -> 用户）
	let (msg_tx, msg_rx) = mpsc::channel::<CanMessage>(100);

	// 发送初始设置
	{
		let settings = build_settings_frame(
			config.can_speed as u8,
			config.can_mode as u8,
			config.frame_type as u8,
			config.filter_id,
			config.mask_id,
		);
		let mut port = serial.lock().await;
		port.write_all(&settings).await?;
		port.flush().await?;
		sleep(Duration::from_millis(100)).await;
	}
	info!("Settings sent successfully");

	// 启动后台任务
	tokio::spawn(split_background_task(
		serial,
		frame_rx,
		msg_tx,
		config,
	));

	let sender = CanUsbSender { frame_tx };

	Ok((sender, msg_rx))
}

/// Split 模式的后台任务：分离的读取和写入任务
///
/// 方案：启动两个任务，一个专门写，一个专门读
/// 避免 Mutex 竞争，利用串口全双工特性
async fn split_background_task(
	serial: Arc<Mutex<tokio_serial::SerialStream>>,
	mut frame_rx: mpsc::Receiver<Frame>,
	msg_tx: mpsc::Sender<CanMessage>,
	config: CanUsbConfig,
) {
	// 创建内部 channel 用于两个任务间协调（如果需要）
	// 但串口是全双工的，读写可以真正并行

	let serial_read = serial.clone();
	let serial_write = serial;

	let config_read = config.clone();
	let config_write = config;

	// 读取任务
	let read_task = tokio::spawn(async move {
		let mut rx_buffer = vec![0u8; 1024];
		let mut rx_length: usize = 0;
		let mut temp = vec![0u8; 256];

		loop {
			// 获取锁读取
			let bytes_read = {
				let mut port = match timeout(Duration::from_millis(100), serial_read.lock()).await {
					Ok(p) => p,
					Err(_) => continue, // 获取锁超时，重试
				};

				match timeout(Duration::from_millis(50), port.read(&mut temp)).await {
					Ok(Ok(n)) => n,
					Ok(Err(e)) => {
						error!("Serial read error: {}", e);
						return;
					}
					Err(_) => 0, // 读超时
				}
			};

			if bytes_read == 0 {
				sleep(Duration::from_micros(100)).await;
				continue;
			}

			if config_read.debug_traffic {
				trace!("RX raw: {:02x?}", &temp[..bytes_read]);
			}

			// 复制到缓冲区
			if rx_length + bytes_read > rx_buffer.len() {
				rx_length = 0;
			}
			rx_buffer[rx_length..rx_length + bytes_read]
				.copy_from_slice(&temp[..bytes_read]);
			rx_length += bytes_read;

			// 解析帧
			let mut parsed_frames = Vec::new();
			let consumed = parse_frames(
				&rx_buffer[..rx_length],
				&mut parsed_frames,
				config_read.debug_traffic
			);

			if consumed > 0 {
				rx_buffer.copy_within(consumed..rx_length, 0);
				rx_length -= consumed;
			}

			// 发送消息
			for parsed in parsed_frames {
				let can_id = if parsed.is_extended {
					CanId::Extended(parsed.id as u32)
				} else {
					CanId::Std(parsed.id)
				};

				let msg = CanMessage::new(can_id, &parsed.data);

				if msg_tx.send(msg).await.is_err() {
					error!("Message channel closed, read task exiting");
					return;
				}
			}
		}
	});

	// 写入任务
	let write_task = tokio::spawn(async move {
		while let Some(frame) = frame_rx.recv().await {
			// 构建数据帧
			let data = match build_data_frame(
				frame.frame_type,
				frame.id().raw(),
				frame.data()
			) {
				Ok(d) => d,
				Err(_) => {
					error!("Frame too large, dropping");
					continue;
				}
			};

			// 获取锁写入
			let mut port = match timeout(Duration::from_secs(5), serial_write.lock()).await {
				Ok(p) => p,
				Err(_) => {
					error!("Timeout acquiring serial lock for write");
					continue;
				}
			};

			if config_write.debug_traffic {
				trace!("TX: {:02x?}", data);
			}

			if let Err(e) = port.write_all(&data).await {
				error!("Serial write error: {}", e);
				return;
			}
			if let Err(e) = port.flush().await {
				error!("Serial flush error: {}", e);
				return;
			}
		}

		info!("Frame channel closed, write task exiting");
	});

	// 等待任一任务结束
	tokio::select! {
        _ = read_task => error!("Read task exited"),
        _ = write_task => error!("Write task exited"),
    }

	error!("Split background task exited!");
}

// ============================================
// Client 模式：独占式读写
// ============================================

/// 独占式客户端，同时只能进行 read 或 write
pub struct CanUsbClient {
	serial: tokio_serial::SerialStream,
	config: CanUsbConfig,
	rx_buffer: Vec<u8>,
	rx_length: usize,
	temp: Vec<u8>,
}

impl CanUsbClient {
	/// 创建新的 Client 模式（独占串口）
	pub async fn new(config: CanUsbConfig) -> Result<Self, ClientError> {
		info!("Creating Client mode: {} @ {} baud", config.device, config.baudrate);

		let serial = tokio_serial::new(&config.device, config.baudrate)
			.data_bits(tokio_serial::DataBits::Eight)
			.stop_bits(tokio_serial::StopBits::Two)
			.parity(tokio_serial::Parity::None)
			.open_native_async()?;

		let mut client = Self {
			serial,
			config: config.clone(),
			rx_buffer: vec![0u8; 1024],
			rx_length: 0,
			temp: vec![0u8; 256],
		};

		client.send_settings().await?;

		Ok(client)
	}

	async fn send_settings(&mut self) -> Result<(), ClientError> {
		let frame = build_settings_frame(
			self.config.can_speed as u8,
			self.config.can_mode as u8,
			self.config.frame_type as u8,
			self.config.filter_id,
			self.config.mask_id,
		);
		self.serial.write_all(&frame).await?;
		self.serial.flush().await?;
		sleep(Duration::from_millis(100)).await;
		info!("Settings sent successfully");
		Ok(())
	}

	pub async fn write(&mut self, frame: &Frame) -> Result<(), ClientError> {
		let data = build_data_frame(frame.frame_type, frame.id().raw(), frame.data())
			.map_err(|_| ClientError::FrameTooLarge)?;

		if self.config.debug_traffic {
			trace!("TX: {:02x?}", data);
		}

		self.serial.write_all(&data).await?;
		self.serial.flush().await?;
		Ok(())
	}

	pub async fn read(&mut self, timeout_duration: Duration) -> Result<CanMessage, ClientError> {
		let deadline = tokio::time::Instant::now() + timeout_duration;

		loop {
			// 先尝试解析缓冲区
			let mut parsed_frames = Vec::new();
			let consumed = parse_frames(&self.rx_buffer[..self.rx_length], &mut parsed_frames, false);

			if consumed > 0 {
				self.rx_buffer.copy_within(consumed..self.rx_length, 0);
				self.rx_length -= consumed;
			}

			if let Some(parsed) = parsed_frames.into_iter().next() {
				let can_id = if parsed.is_extended {
					CanId::Extended(parsed.id as u32)
				} else {
					CanId::Std(parsed.id)
				};
				return Ok(CanMessage::new(can_id, &parsed.data));
			}

			let now = tokio::time::Instant::now();
			if now >= deadline {
				return Err(ClientError::ReadTimeout);
			}
			let remaining = deadline - now;

			match timeout(remaining, self.serial.read(&mut self.temp)).await {
				Ok(Ok(0)) => {
					return Err(ClientError::Io(std::io::Error::new(
						std::io::ErrorKind::UnexpectedEof,
						"Serial port closed"
					)));
				}
				Ok(Ok(n)) => {
					if self.config.debug_traffic {
						trace!("RX raw: {:02x?}", &self.temp[..n]);
					}

					if self.rx_length + n > self.rx_buffer.len() {
						self.rx_length = 0;
					}
					self.rx_buffer[self.rx_length..self.rx_length + n]
						.copy_from_slice(&self.temp[..n]);
					self.rx_length += n;
				}
				Ok(Err(e)) => return Err(e.into()),
				Err(_) => return Err(ClientError::ReadTimeout),
			}
		}
	}

	pub fn try_read(&mut self) -> Result<Option<CanMessage>, ClientError> {
		let mut parsed_frames = Vec::new();
		let consumed = parse_frames(&self.rx_buffer[..self.rx_length], &mut parsed_frames, false);

		if consumed > 0 {
			self.rx_buffer.copy_within(consumed..self.rx_length, 0);
			self.rx_length -= consumed;
		}

		Ok(parsed_frames.into_iter().next().map(|parsed| {
			let can_id = if parsed.is_extended {
				CanId::Extended(parsed.id as u32)
			} else {
				CanId::Std(parsed.id)
			};
			CanMessage::new(can_id, &parsed.data)
		}))
	}
}

/// 便捷函数：直接创建 Client 模式
pub async fn client(config: CanUsbConfig) -> Result<CanUsbClient, ClientError> {
	CanUsbClient::new(config).await
}
